name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Lint, Build, Test
    runs-on: macOS-latest
    permissions:
      checks: write
    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Mise
        uses: jdx/mise-action@v2
      - name: Lint
        run: make lint
      - name: Install dependencies and generate Xcode workspace
        run: make generate
      - name: Build
        run: make build
      - name: Test
        id: test
        run: make test
      - name: Process XCResult
        uses: lunij/xcresult@v1
        if: success() || failure()
        with:
          path: .derivedData/Netbob.xcresult
          title: XCResult
