name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Lint, Build, Test
    runs-on: macOS-latest
    env:
      derived-data-path: .derivedData
    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Mise
        uses: jdx/mise-action@v2
      - name: Lint
        run: make lint
      - name: Install dependencies and generate Xcode workspace
        run: make generate
      - name: Build
        run: make build
      - name: Test
        id: test
        run: make test
      - name: Zip XCResults
        id: zip-xcresults
        if: failure() && steps.test.conclusion == 'failure'
        run: |
          cd $(dirname $(find ${{ env.derived-data-path }} -name "*.xcresult" | head -n1))
          zip -r xcresults.zip *.xcresult
      - name: Upload XCResults
        if: failure() && steps.zip-xcresults.conclusion == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: xcresults.zip
          path: ./xcresults.zip
